import { Bytes, Hash, Hex } from 'ox'

/**
 * MPP attribution memo encoding for TIP-20 `transferWithMemo`.
 *
 * When no user-provided memo is present, the SDK auto-generates an
 * attribution memo so MPP transactions are identifiable on-chain.
 *
 * ## Byte Layout (32 bytes)
 *
 * | Offset | Size | Field                           |
 * |--------|------|---------------------------------|
 * | 0..3   | 4    | TAG = keccak256("mpp")[0..3]     |
 * | 4      | 1    | version (0x01)                  |
 * | 5..31  | 27   | nonce (random bytes)            |
 *
 * The TAG prefix makes MPP transactions trivially distinguishable
 * from arbitrary memos via `TransferWithMemo` event topic filtering.
 * Server identity is already available via the `to` (recipient) address.
 *
 * @module
 */

/** First 4 bytes of keccak256("mpp") — the on-chain MPP tag. */
export const TAG = Hex.slice(Hash.keccak256(Bytes.fromString('mpp'), { as: 'Hex' }), 0, 4)

/** Current memo version. */
const VERSION = 0x01

/**
 * Encodes an MPP attribution memo as a `bytes32` hex string.
 *
 * @returns A `0x`-prefixed 64-char hex string (32 bytes).
 *
 * @example
 * ```ts
 * import * as Attribution from './Attribution.js'
 *
 * const memo = Attribution.encode()
 * ```
 */
export function encode(): `0x${string}` {
  const buf = new Uint8Array(32)

  // [0..3] TAG
  const tagBytes = Hex.toBytes(TAG)
  buf.set(tagBytes, 0)

  // [4] version
  buf[4] = VERSION

  // [5..31] nonce (27 random bytes)
  const nonce = crypto.getRandomValues(new Uint8Array(27))
  buf.set(nonce, 5)

  return Hex.fromBytes(buf) as `0x${string}`
}

/**
 * Checks whether a memo was generated by the MPP attribution system.
 *
 * @param memo - A `0x`-prefixed hex string (bytes32).
 * @returns `true` if the memo starts with the MPP tag and version byte.
 *
 * @example
 * ```ts
 * import * as Attribution from './Attribution.js'
 *
 * Attribution.isMppMemo(Attribution.encode()) // true
 * Attribution.isMppMemo('0x0000...0000')      // false
 * ```
 */
export function isMppMemo(memo: `0x${string}`): boolean {
  if (memo.length < 12) return false // need at least tag (4 bytes = 8 hex chars) + "0x"
  const memoTag = memo.slice(0, 10) as `0x${string}` // 0x + 8 hex chars = 4 bytes
  const version = Number.parseInt(memo.slice(10, 12), 16)
  return memoTag.toLowerCase() === TAG.toLowerCase() && version === VERSION
}

/**
 * Decodes an MPP attribution memo into its constituent parts.
 *
 * @param memo - A `0x`-prefixed hex string (bytes32).
 * @returns The decoded fields, or `null` if the memo is not an MPP memo.
 *
 * @example
 * ```ts
 * import * as Attribution from './Attribution.js'
 *
 * const memo = Attribution.encode()
 * const decoded = Attribution.decode(memo)
 * // { version: 1, nonce: '0x...' }
 * ```
 */
export function decode(memo: `0x${string}`): decode.Result | null {
  if (!isMppMemo(memo)) return null

  const version = Number.parseInt(memo.slice(10, 12), 16)
  const nonce = `0x${memo.slice(12)}` as `0x${string}` // bytes 5..31

  return { version, nonce }
}

export declare namespace decode {
  type Result = {
    /** Memo version (currently always 1). */
    version: number
    /** 27-byte random nonce hex. */
    nonce: `0x${string}`
  }
}
