import { Bytes, Hash, Hex } from 'ox'

/**
 * MPP attribution memo encoding for TIP-20 `transferWithMemo`.
 *
 * When no user-provided memo is present, the SDK auto-generates an
 * attribution memo so MPP transactions are identifiable on-chain.
 *
 * ## Byte Layout (32 bytes)
 *
 * | Offset | Size | Field                                     |
 * |--------|------|-------------------------------------------|
 * | 0..3   | 4    | TAG = keccak256("mpp")[0..3]               |
 * | 4      | 1    | version (0x01)                            |
 * | 5..14  | 10   | serverId = keccak256(serverId)[0..9]       |
 * | 15..24 | 10   | clientId = keccak256(clientId)[0..9] or 0s |
 * | 25..31 | 7    | nonce (random bytes)                      |
 *
 * The TAG prefix makes MPP transactions trivially distinguishable
 * from arbitrary memos via `TransferWithMemo` event topic filtering.
 *
 * @module
 */

/** First 4 bytes of keccak256("mpp") — the on-chain MPP tag. */
export const TAG = Hex.slice(Hash.keccak256(Bytes.fromString('mpp'), { as: 'Hex' }), 0, 4)

/** Current memo version. */
const VERSION = 0x01

/** 10 zero bytes representing an anonymous (no clientId) client. */
export const ANONYMOUS = '0x00000000000000000000' as `0x${string}`

/**
 * Computes a 10-byte fingerprint from a string via keccak256.
 * @internal
 */
function fingerprint(value: string): Uint8Array {
  const hash = Hash.keccak256(Bytes.fromString(value), { as: 'Hex' })
  return Hex.toBytes(Hex.slice(hash, 0, 10))
}

/**
 * Encodes an MPP attribution memo as a `bytes32` hex string.
 *
 * @param parameters - The serverId (server identity) and optional clientId.
 * @returns A `0x`-prefixed 64-char hex string (32 bytes).
 *
 * @example
 * ```ts
 * import * as Attribution from './Attribution.js'
 *
 * const memo = Attribution.encode({ serverId: 'api.example.com', clientId: 'my-app' })
 * ```
 */
export function encode(parameters: encode.Parameters): `0x${string}` {
  const { serverId, clientId } = parameters
  const buf = new Uint8Array(32)

  // [0..3] TAG
  buf.set(Hex.toBytes(TAG), 0)

  // [4] version
  buf[4] = VERSION

  // [5..14] server fingerprint (10 bytes)
  buf.set(fingerprint(serverId), 5)

  // [15..24] client fingerprint or zero bytes (10 bytes)
  if (clientId) buf.set(fingerprint(clientId), 15)
  // else: already zero-filled

  // [25..31] nonce (7 random bytes)
  const nonce = crypto.getRandomValues(new Uint8Array(7))
  buf.set(nonce, 25)

  return Hex.fromBytes(buf) as `0x${string}`
}

export declare namespace encode {
  type Parameters = {
    /** Server identity used to derive the server fingerprint. */
    serverId: string
    /** Optional client identity used to derive the client fingerprint. */
    clientId?: string | undefined
  }
}

/**
 * Checks whether a memo was generated by the MPP attribution system.
 *
 * @param memo - A `0x`-prefixed hex string (bytes32).
 * @returns `true` if the memo starts with the MPP tag and version byte.
 *
 * @example
 * ```ts
 * import * as Attribution from './Attribution.js'
 *
 * Attribution.isMppMemo(Attribution.encode({ serverId: 'api.example.com' })) // true
 * Attribution.isMppMemo('0x0000...0000')      // false
 * ```
 */
export function isMppMemo(memo: `0x${string}`): boolean {
  if (memo.length !== 66) return false // v1 is exactly 32 bytes (0x + 64 hex chars)
  const memoTag = memo.slice(0, 10) as `0x${string}` // 0x + 8 hex chars = 4 bytes
  const version = Number.parseInt(memo.slice(10, 12), 16)
  return memoTag.toLowerCase() === TAG.toLowerCase() && version === VERSION
}

/**
 * Verifies that a memo's server fingerprint matches the given serverId.
 *
 * Checks TAG, version byte, and that bytes 5–14 equal keccak256(serverId)[0..9].
 *
 * @param memo - A `0x`-prefixed hex string (bytes32).
 * @param serverId - The expected server identity.
 * @returns `true` if the memo has a valid MPP tag and matching server fingerprint.
 */
export function verifyServer(memo: `0x${string}`, serverId: string): boolean {
  if (!isMppMemo(memo)) return false
  const memoServerHex = `0x${memo.slice(12, 32)}` as `0x${string}` // bytes 5..14 = 10 bytes = 20 hex chars
  const expectedHex = Hex.fromBytes(fingerprint(serverId)) as `0x${string}`
  return memoServerHex.toLowerCase() === expectedHex.toLowerCase()
}

/**
 * Decodes an MPP attribution memo into its constituent parts.
 *
 * @param memo - A `0x`-prefixed hex string (bytes32).
 * @returns The decoded fields, or `null` if the memo is not an MPP memo.
 *
 * @example
 * ```ts
 * import * as Attribution from './Attribution.js'
 *
 * const memo = Attribution.encode({ serverId: 'api.example.com', clientId: 'my-app' })
 * const decoded = Attribution.decode(memo)
 * // { version: 1, serverId: '0x...', clientId: '0x...', nonce: '0x...' }
 * ```
 */
export function decode(memo: `0x${string}`): decode.Result | null {
  if (!isMppMemo(memo)) return null

  const version = Number.parseInt(memo.slice(10, 12), 16)
  const serverId = `0x${memo.slice(12, 32)}` as `0x${string}` // bytes 5..14
  const clientHex = `0x${memo.slice(32, 52)}` as `0x${string}` // bytes 15..24
  const nonce = `0x${memo.slice(52)}` as `0x${string}` // bytes 25..31

  const clientId = clientHex.toLowerCase() === ANONYMOUS.toLowerCase() ? null : clientHex

  return { version, serverId, clientId, nonce }
}

export declare namespace decode {
  type Result = {
    /** Memo version (currently always 1). */
    version: number
    /** 10-byte server fingerprint hex (keccak256(serverId)[0..9]). */
    serverId: `0x${string}`
    /** 10-byte client fingerprint hex, or `null` if anonymous. */
    clientId: `0x${string}` | null
    /** 7-byte random nonce hex. */
    nonce: `0x${string}`
  }
}
