// Generated by scripts/sync-version.ts.

/** Current mppx package version. */
export const version = '0.10.1'

/** Canonical SDK identifier for this mppx release. */
export const sdkIdentifier = `mppx/${version}`
