import * as crypto from 'node:crypto'
import * as fs from 'node:fs/promises'
import * as path from 'node:path'

import { defineConfig } from 'vite'

let root: string

export default defineConfig({
  plugins: [
    {
      name: 'mppx:page_emit',
      apply: 'build',
      config: () => ({
        build: {
          outDir: 'dist',
          emptyOutDir: true,
          rolldownOptions: {
            input: 'src/page.ts',
            output: { entryFileNames: '[name].js', format: 'es' as const },
          },
          modulePreload: false,
          minify: true,
        },
      }),
      configResolved(config) {
        root = config.root
      },
      async closeBundle() {
        const output = path.resolve(root, '../../server/internal/html.gen.ts')
        // Build service worker separately (different global scope)
        const { build } = await import('vite')
        await build({
          root,
          logLevel: 'warn',
          configFile: false,
          build: {
            outDir: 'dist',
            emptyOutDir: false,
            rolldownOptions: {
              input: path.resolve(root, 'src/serviceWorker.ts'),
              output: { entryFileNames: 'serviceWorker.js', format: 'es' },
            },
            minify: true,
            modulePreload: false,
          },
        })

        const pageContent = (
          await fs.readFile(path.resolve(root, 'src/page.html'), 'utf-8')
        ).trimEnd()
        const pageBundledScript = escapeTemplateLiteral(
          (await fs.readFile(path.resolve(root, 'dist/page.js'), 'utf-8')).trim(),
        )
        const pageScript = `\n  <script type="module">\n${indent(pageBundledScript, 4)}\n  </script>`
        const serviceWorkerScript = (
          await fs.readFile(path.resolve(root, 'dist/serviceWorker.js'), 'utf-8')
        ).trim()

        const body = [
          `export const content = \`\n${pageContent}\``,
          ``,
          `export const script = \`${pageScript}\n  \``,
          ``,
          `export const serviceWorker = ${JSON.stringify(serviceWorkerScript)}`,
        ].join('\n')
        const file = [comment(body), ``, body].join('\n')

        await fs.mkdir(path.dirname(output), { recursive: true })
        await fs.writeFile(output, file + '\n')
        console.log(`  Wrote ${output}`)
      },
    },
  ],
})

function comment(body: string): string {
  const hash = crypto.createHash('md5').update(body).digest('hex')
  return `/* oxlint-disable */\n// Generated by \`pnpm build:html\` (hash: ${hash})`
}

function escapeTemplateLiteral(str: string): string {
  return str
    .replace(/\/\/# sourceMappingURL=.*$/m, '')
    .trim()
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')
}

function indent(str: string, spaces: number): string {
  const pad = ' '.repeat(spaces)
  return str
    .split('\n')
    .map((line) => (line.trim() ? pad + line : line))
    .join('\n')
}
