name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Lint & format
        run: pnpm check:ci

      - name: Check types
        run: pnpm check:types

  test:
    name: Test Runtime
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-docker-action@v4

      - name: Install secret-tool (libsecret)
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-tools gnome-keyring dbus-x11

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run tests
        run: |
          eval "$(dbus-launch --sh-syntax)"
          echo '' | gnome-keyring-daemon --unlock --components=secrets
          pnpm run test --bail=1
        env:
          CI: true
